---
- hosts: "{{hosts}}"
  become: yes
 
  tasks:
    - name: Install packages
      yum: name={{item}} state=present
      with_items:
        - git
          #- subversion
    - name: pack-vcs variable trace
      debug: 'msg="hosts: {{hosts}}"'
