---
- hosts: "{{hosts}}"
  become: yes
 
  tasks:
    - name: Install packages
      package: name={{item}} state=present
      with_items:
        - bzip2
        - dos2unix
        - unzip
        - man
        - tar
        - curl
        - rsync
        - vim
        - nano
        - bind-utils
        - libselinux-python
    - name: pack variable trace
      debug: 'msg="hosts: {{hosts}}"'
