---
- hosts: "{{hosts}}"
  become: yes
 
  tasks:
    - name: Install packages
      yum: name={{item}} state=present
      with_items:
        - bzip2
        - dos2unix
        - unzip
        - man
        - tar
        - curl
        - rsync
        - vim
        - nano
        - bind-utils
        - libselinux-python
        - git
        - subversion
    - name: yum variable trace
      debug: 'msg="hosts: {{hosts}}"'
